[project]
name = "msk-communicator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "jinja2>=3.1.6",
    "microdot>=2.5.1",
    "pyjwt>=2.0.0",
]
